/*
LocalizableConstants.swift

GENERATED - DO NOT MODIFY - use localio instead.

Created by localio
*/

import Foundation


let kLocaleAppName: String = { return NSLocalizedString("app_name", comment: "") }()
let kLocaleButtonOk: String = { return NSLocalizedString("button_ok", comment: "") }()
let kLocaleAlertButtonYes: String = { return NSLocalizedString("alert_button_yes", comment: "") }()
let kLocaleButtonAccept: String = { return NSLocalizedString("button_accept", comment: "") }()
let kLocaleButtonRetry: String = { return NSLocalizedString("button_retry", comment: "") }()
let kLocaleButtonCancel: String = { return NSLocalizedString("button_cancel", comment: "") }()
let kLocaleButtonLogin: String = { return NSLocalizedString("button_login", comment: "") }()
let kLocaleNavigationButtonClose: String = { return NSLocalizedString("navigation_button_close", comment: "") }()
let kLocaleLogOut: String = { return NSLocalizedString("log_out", comment: "") }()
let kLocaleTermsAndConditions: String = { return NSLocalizedString("terms_and_conditions", comment: "") }()
let kLocaleErrorHasToAcceptTerms: String = { return NSLocalizedString("error_has_to_accept_terms", comment: "") }()
let kLocaleErrorUnexpected: String = { return NSLocalizedString("error_unexpected", comment: "") }()
let kLocaleErrorNoInternet: String = { return NSLocalizedString("error_no_internet", comment: "") }()
let kLocaleErrorTimeout: String = { return NSLocalizedString("error_timeout", comment: "") }()
let kLocaleErrorLocationDisabled: String = { return NSLocalizedString("error_location_disabled", comment: "") }()
let kLocaleErrorCountryUnavailable: String = { return NSLocalizedString("error_country_unavailable", comment: "") }()
let kLocaleErrorRetry: String = { return NSLocalizedString("error_retry", comment: "") }()
let kLocaleErrorGettingContent: String = { return NSLocalizedString("error_getting_content", comment: "") }()
let kLocaleErrorGettingContentTitle: String = { return NSLocalizedString("error_getting_content_title", comment: "") }()
let kLocaleErrorGettingContentDescription: String = { return NSLocalizedString("error_getting_content_description", comment: "") }()
let kLocaleErrorGooglePlayServices: String = { return NSLocalizedString("error_google_play_services", comment: "") }()
let kLocaleWelcomeButtonGetStarted: String = { return NSLocalizedString("welcome_button_get_started", comment: "") }()
let kLocaleWelcomeLabelTerms: String = { return NSLocalizedString("welcome_label_terms", comment: "") }()
let kLocaleLoginNotificationLabel: String = { return NSLocalizedString("login_notification_label", comment: "") }()
let kLocaleLoginNotificationTitleLabel: String = { return NSLocalizedString("login_notification_title_label", comment: "") }()
let kLocaleLoginProfileSettings: String = { return NSLocalizedString("login_profile_settings", comment: "") }()
let kLocaleLoginTitle: String = { return NSLocalizedString("login_title", comment: "") }()
let kLocaleLoginEditProfileTitle: String = { return NSLocalizedString("login_edit_profile_title", comment: "") }()
let kLocaleLoginFeedbackUs: String = { return NSLocalizedString("login_feedback_us", comment: "") }()
let kLocaleLoginTermsAndConditions: String = { return NSLocalizedString("login_terms_and_conditions", comment: "") }()
let kLocaleHomeLoadingTitle: String = { return NSLocalizedString("home_loading_title", comment: "") }()
let kLocaleNoContentTitle: String = { return NSLocalizedString("no_content_title", comment: "") }()
let kLocaleNoContentTitleText1: String = { return NSLocalizedString("no_content_title_text1", comment: "") }()
let kLocaleNoContentTitleText2: String = { return NSLocalizedString("no_content_title_text2", comment: "") }()
let kLocaleNoContentTitleText3: String = { return NSLocalizedString("no_content_title_text3", comment: "") }()
let kLocaleNoContentButton: String = { return NSLocalizedString("no_content_button", comment: "") }()
let kLocalePreviewSlideText: String = { return NSLocalizedString("preview_slide_text", comment: "") }()
let kLocaleSearchNoResults: String = { return NSLocalizedString("search_no_results", comment: "") }()
let kLocaleSearchNoResultsTitle: String = { return NSLocalizedString("search_no_results_title", comment: "") }()
let kLocaleSearchNoResultsDescription: String = { return NSLocalizedString("search_no_results_description", comment: "") }()
let kLocaleHintSearcherText: String = { return NSLocalizedString("hint_searcher_text", comment: "") }()
let kLocaleOxScannerToolbarTitle: String = { return NSLocalizedString("ox_scanner_toolbar_title", comment: "") }()
let kLocaleOxWebviewToolbarTitle: String = { return NSLocalizedString("ox_webview_toolbar_title", comment: "") }()
let kLocaleOxPermissionSettings: String = { return NSLocalizedString("ox_permission_settings", comment: "") }()
let kLocaleOxPermissionDeniedGeolocation: String = { return NSLocalizedString("ox_permission_denied_geolocation", comment: "") }()
let kLocaleOxPermissionRationaleTitleLocation: String = { return NSLocalizedString("ox_permission_rationale_title_location", comment: "") }()
let kLocaleOxPermissionRationaleMessageLocation: String = { return NSLocalizedString("ox_permission_rationale_message_location", comment: "") }()
let kLocaleIrAppName: String = { return NSLocalizedString("ir_app_name", comment: "") }()
let kLocaleIrLoadingIndicatorMessage: String = { return NSLocalizedString("ir_loading_indicator_message", comment: "") }()
let kLocaleIrPermissionSettings: String = { return NSLocalizedString("ir_permission_settings", comment: "") }()
let kLocaleIrPermissionDeniedCamera: String = { return NSLocalizedString("ir_permission_denied_camera", comment: "") }()
let kLocaleIrPermissionRationaleTitleCamera: String = { return NSLocalizedString("ir_permission_rationale_title_camera", comment: "") }()
let kLocaleIrPermissionRationaleMessageCamera: String = { return NSLocalizedString("ir_permission_rationale_message_camera", comment: "") }()
let kLocaleOcmErrorContent: String = { return NSLocalizedString("ocm_error_content", comment: "") }()
