/*
LocalizableConstants.swift

GENERATED - DO NOT MODIFY - use localio instead.

Created by localio
*/

import Foundation


let kLocaleAppName: String = { return NSLocalizedString("app_name", comment: "") }()
let kLocaleOk: String = { return NSLocalizedString("ok", comment: "") }()
let kLocaleActionEdit: String = { return NSLocalizedString("action_edit", comment: "") }()
let kLocaleActionMyCoupons: String = { return NSLocalizedString("action_my_coupons", comment: "") }()
let kLocaleActionSave: String = { return NSLocalizedString("action_save", comment: "") }()
let kLocaleActionSettings: String = { return NSLocalizedString("action_settings", comment: "") }()
let kLocaleActionShare: String = { return NSLocalizedString("action_share", comment: "") }()
let kLocaleActionRetry: String = { return NSLocalizedString("action_retry", comment: "") }()
let kLocaleErrorUnexpected: String = { return NSLocalizedString("error_unexpected", comment: "") }()
let kLocaleErrorNoInternet: String = { return NSLocalizedString("error_no_internet", comment: "") }()
let kLocaleErrorTimeout: String = { return NSLocalizedString("error_timeout", comment: "") }()
let kLocaleErrorPassbookUnsupportedVersion: String = { return NSLocalizedString("error_passbook_unsupported_version", comment: "") }()
let kLocaleErrorRequiredField: String = { return NSLocalizedString("error_required_field", comment: "") }()
let kLocaleErrorLoginMailFormat: String = { return NSLocalizedString("error_login_mail_format", comment: "") }()
let kLocaleErrorLoginMessage: String = { return NSLocalizedString("error_login_message", comment: "") }()
let kLocaleErrorRegisterCountry: String = { return NSLocalizedString("error_register_country", comment: "") }()
let kLocaleErrorRegisterGender: String = { return NSLocalizedString("error_register_gender", comment: "") }()
let kLocaleErrorScannerCameradisable: String = { return NSLocalizedString("error_scanner_cameradisable", comment: "") }()
let kLocaleErrorNotUrlFormat: String = { return NSLocalizedString("error_not_url_format", comment: "") }()
let kLocaleErrorNotValidPdf: String = { return NSLocalizedString("error_not_valid_pdf", comment: "") }()
let kLocaleErrorUserDeleted: String = { return NSLocalizedString("error_user_deleted", comment: "") }()
let kLocaleErrorUserExist: String = { return NSLocalizedString("error_user_exist", comment: "") }()
let kLocaleErrorUserNotExist: String = { return NSLocalizedString("error_user_not_exist", comment: "") }()
let kLocaleAlertButtonRetry: String = { return NSLocalizedString("alert_button_retry", comment: "") }()
let kLocaleAlertRegisterSuccessTitle: String = { return NSLocalizedString("alert_register_success_title", comment: "") }()
let kLocaleAlertRegisterSuccessBody: String = { return NSLocalizedString("alert_register_success_body", comment: "") }()
let kLocaleAlertDialogButtonAccept: String = { return NSLocalizedString("alert_dialog_button_accept", comment: "") }()
let kLocaleAlertDialogButtonCancel: String = { return NSLocalizedString("alert_dialog_button_cancel", comment: "") }()
let kLocaleAlertDialogTextResetPassword: String = { return NSLocalizedString("alert_dialog_text_reset_password", comment: "") }()
let kLocaleAlertDialogResetPasswordTitle: String = { return NSLocalizedString("alert_dialog_reset_password_title", comment: "") }()
let kLocaleAlertDialogResetPasswordBody: String = { return NSLocalizedString("alert_dialog_reset_password_body", comment: "") }()
let kLocaleAlertTextEmail: String = { return NSLocalizedString("alert_text_email", comment: "") }()
let kLocaleAlertValidatorSamePasswords: String = { return NSLocalizedString("alert_validator_same_passwords", comment: "") }()
let kLocaleAlertValidatorEmptyField: String = { return NSLocalizedString("alert_validator_empty_field", comment: "") }()
let kLocaleAlertProfileDeleteConfirmation: String = { return NSLocalizedString("alert_profile_delete_confirmation", comment: "") }()
let kLocaleAlertProfileLogoutConfirmation: String = { return NSLocalizedString("alert_profile_logout_confirmation", comment: "") }()
let kLocaleAlertGoToGooglePlayText: String = { return NSLocalizedString("alert_go_to_google_play_text", comment: "") }()
let kLocaleAlertGoToAppleStoreText: String = { return NSLocalizedString("alert_go_to_apple_store_text", comment: "") }()
let kLocaleAlertSaveSuccessful: String = { return NSLocalizedString("alert_save_successful", comment: "") }()
let kLocaleWelcomeButtonLogin: String = { return NSLocalizedString("welcome_button_login", comment: "") }()
let kLocaleWelcomeButtonRegister: String = { return NSLocalizedString("welcome_button_register", comment: "") }()
let kLocaleLoginTextUser: String = { return NSLocalizedString("login_text_user", comment: "") }()
let kLocaleLoginTextPassword: String = { return NSLocalizedString("login_text_password", comment: "") }()
let kLocaleLoginTextAccess: String = { return NSLocalizedString("login_text_access", comment: "") }()
let kLocaleLoginButtonFacebookAccess: String = { return NSLocalizedString("login_button_facebook_access", comment: "") }()
let kLocaleLoginTextForgotPassword: String = { return NSLocalizedString("login_text_forgot_password", comment: "") }()
let kLocaleLoginTextRegister: String = { return NSLocalizedString("login_text_register", comment: "") }()
let kLocaleRegisterButtonFacebook: String = { return NSLocalizedString("register_button_facebook", comment: "") }()
let kLocaleRegisterTextMail: String = { return NSLocalizedString("register_text_mail", comment: "") }()
let kLocaleRegisterTextFacebookComplete: String = { return NSLocalizedString("register_text_facebook_complete", comment: "") }()
let kLocaleRegisterTextName: String = { return NSLocalizedString("register_text_name", comment: "") }()
let kLocaleRegisterTextLastname: String = { return NSLocalizedString("register_text_lastname", comment: "") }()
let kLocaleRegisterTextEmail: String = { return NSLocalizedString("register_text_email", comment: "") }()
let kLocaleRegisterTextConfirmPassword: String = { return NSLocalizedString("register_text_confirm_password", comment: "") }()
let kLocaleRegisterTextGender: String = { return NSLocalizedString("register_text_gender", comment: "") }()
let kLocaleRegisterTextBirthdate: String = { return NSLocalizedString("register_text_birthdate", comment: "") }()
let kLocaleRegisterTextCountry: String = { return NSLocalizedString("register_text_country", comment: "") }()
let kLocaleRegisterButton: String = { return NSLocalizedString("register_button", comment: "") }()
let kLocaleRegisterTextTerms: String = { return NSLocalizedString("register_text_terms", comment: "") }()
let kLocaleRegisterTextTermsHtml: String = { return NSLocalizedString("register_text_terms_html", comment: "") }()
let kLocaleRegisterTextMan: String = { return NSLocalizedString("register_text_man", comment: "") }()
let kLocaleRegisterTextWoman: String = { return NSLocalizedString("register_text_woman", comment: "") }()
let kLocaleRegisterTitleTerms: String = { return NSLocalizedString("register_title_terms", comment: "") }()
let kLocaleMenuSectionHome: String = { return NSLocalizedString("menu_section_home", comment: "") }()
let kLocaleMenuSectionCuopons: String = { return NSLocalizedString("menu_section_cuopons", comment: "") }()
let kLocaleMenuSectionRestaurants: String = { return NSLocalizedString("menu_section_restaurants", comment: "") }()
let kLocaleMenuSectionProducts: String = { return NSLocalizedString("menu_section_products", comment: "") }()
let kLocaleMenuSectionProfile: String = { return NSLocalizedString("menu_section_profile", comment: "") }()
let kLocaleMenuSectionConfiguration: String = { return NSLocalizedString("menu_section_configuration", comment: "") }()
let kLocaleMenuSectionInstitucional: String = { return NSLocalizedString("menu_section_institucional", comment: "") }()
let kLocaleMenuSectionAbout: String = { return NSLocalizedString("menu_section_about", comment: "") }()
let kLocaleMenuSectionQr: String = { return NSLocalizedString("menu_section_qr", comment: "") }()
let kLocaleCouponsDetailButtonObtain: String = { return NSLocalizedString("coupons_detail_button_obtain", comment: "") }()
let kLocaleCouponsCampaignsEmpty: String = { return NSLocalizedString("coupons_campaigns_empty", comment: "") }()
let kLocaleCouponsCampaignsEmptyComeBack: String = { return NSLocalizedString("coupons_campaigns_empty_come_back", comment: "") }()
let kLocaleCouponsDetailLabelCode: String = { return NSLocalizedString("coupons_detail_label_code", comment: "") }()
let kLocaleCouponsDetailButtonPdf: String = { return NSLocalizedString("coupons_detail_button_pdf", comment: "") }()
let kLocaleCouponsDetailButtonWalletAdd: String = { return NSLocalizedString("coupons_detail_button_wallet_add", comment: "") }()
let kLocaleCouponsDetailButtonAppleWallet: String = { return NSLocalizedString("coupons_detail_button_apple_wallet", comment: "") }()
let kLocaleCouponsUserSegmentActive: String = { return NSLocalizedString("coupons_user_segment_active", comment: "") }()
let kLocaleCouponsUserSegmentExpired: String = { return NSLocalizedString("coupons_user_segment_expired", comment: "") }()
let kLocaleCouponsUserLabelEmptyListActive: String = { return NSLocalizedString("coupons_user_label_empty_list_active", comment: "") }()
let kLocaleCouponsUserLabelEmptyListExpired: String = { return NSLocalizedString("coupons_user_label_empty_list_expired", comment: "") }()
let kLocaleCouponSectionTitle: String = { return NSLocalizedString("coupon_section_title", comment: "") }()
let kLocaleCouponsDetailTitle: String = { return NSLocalizedString("coupons_detail_title", comment: "") }()
let kLocaleCouponsCampaignsdetailTitle: String = { return NSLocalizedString("coupons_campaignsdetail_title", comment: "") }()
let kLocaleCouponsUserRibbondays: String = { return NSLocalizedString("coupons_user_ribbondays", comment: "") }()
let kLocaleCouponsUserRibbonday: String = { return NSLocalizedString("coupons_user_ribbonday", comment: "") }()
let kLocaleCouponsUserToday: String = { return NSLocalizedString("coupons_user_today", comment: "") }()
let kLocaleCouponsErrorExpiredCoupon: String = { return NSLocalizedString("coupons_error_expired_coupon", comment: "") }()
let kLocaleCouponsSendTo: String = { return NSLocalizedString("coupons_send_to", comment: "") }()
let kLocaleCouponsLocalnotificationSend: String = { return NSLocalizedString("coupons_localnotification_send", comment: "") }()
let kLocaleQrScannerDefaultlabel: String = { return NSLocalizedString("qr_scanner_defaultlabel", comment: "") }()
let kLocaleQrPermissionSettings: String = { return NSLocalizedString("qr_permission_settings", comment: "") }()
let kLocaleQrPermissionDeniedCamera: String = { return NSLocalizedString("qr_permission_denied_camera", comment: "") }()
let kLocaleQrPermissionRationaleTitleCamera: String = { return NSLocalizedString("qr_permission_rationale_title_camera", comment: "") }()
let kLocaleBrowserWebviewTitle: String = { return NSLocalizedString("browser_webview_title", comment: "") }()
let kLocaleProfileTextCurrentPassword: String = { return NSLocalizedString("profile_text_current_password", comment: "") }()
let kLocaleProfileTextNewPassword: String = { return NSLocalizedString("profile_text_new_password", comment: "") }()
let kLocaleProfileTextConfirmPassword: String = { return NSLocalizedString("profile_text_confirm_password", comment: "") }()
let kLocaleProfileButtonShowVoucher: String = { return NSLocalizedString("profile_button_show_voucher", comment: "") }()
let kLocaleProfileButtonCloseSession: String = { return NSLocalizedString("profile_button_close_session", comment: "") }()
let kLocaleProfileButtonRemoveAccount: String = { return NSLocalizedString("profile_button_remove_account", comment: "") }()
let kLocaleProfileRemoveAccountMessage: String = { return NSLocalizedString("profile_remove_account_message", comment: "") }()
let kLocaleConfigurationTextNotifications: String = { return NSLocalizedString("configuration_text_notifications", comment: "") }()
let kLocaleConfigurationTextCountrySelected: String = { return NSLocalizedString("configuration_text_country_selected", comment: "") }()
let kLocaleConfigurationTextSelectCountry: String = { return NSLocalizedString("configuration_text_select_country", comment: "") }()
